# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Syz44cxOVQuJmA5GY6DQLqt_1t7c-Cn
"""

!pip install tensorflow opencv-python pandas matplotlib seaborn scikit-learn

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score
)

from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Dropout
)

import kagglehub

df = pd.read_csv(
    "/kaggle/input/fashion-product-images-small/styles.csv",
    on_bad_lines='skip'
)

print(df.shape)
df.head()

df = pd.read_csv(
    "/kaggle/input/fashion-product-images-small/styles.csv",
    on_bad_lines='skip'
)

print(df.shape)
df.head()

print(df.isnull().sum())

df.dropna(inplace=True)

print(df.shape)

df.isnull().sum()

df = df[['id','articleType']]

df

top_categories = (
    df['articleType']
    .value_counts()
    .head(10)
    .index
)

df = df[
    df['articleType'].isin(top_categories)
]

print(df.shape)

image_dir = "/kaggle/input/fashion-product-images-small/images"

df['image_path'] = (
    image_dir + "/"
    + df['id'].astype(str)
    + ".jpg"
)

df = df[
    df['image_path'].apply(os.path.exists)
]

print(df.shape)

plt.figure(figsize=(10,8))

for i in range(9):

    plt.subplot(3,3,i+1)

    img = Image.open(
        df.iloc[i]['image_path']
    )

    plt.imshow(img)

    plt.title(
        df.iloc[i]['articleType']
    )

    plt.axis("off")

plt.show()

plt.figure(figsize=(12,5))

sns.countplot(
    y=df['articleType'],
    order=df['articleType'].value_counts().index
)

plt.title("Article Type Distribution")
plt.show()

le = LabelEncoder()

df['label'] = le.fit_transform(
    df['articleType']
)

num_classes = len(
    df['label'].unique()
)

print("Classes:", num_classes)

df = df.sample(
    5000,
    random_state=42
)

IMG_SIZE = 128

images = []
labels = []

for _, row in df.iterrows():

    try:

        img = load_img(
            row['image_path'],
            target_size=(IMG_SIZE,IMG_SIZE)
        )

        img = img_to_array(img)

        img = img / 255.0

        images.append(img)

        labels.append(row['label'])

    except:
        pass

X = np.array(images)

y = np.array(labels)

print(X.shape)
print(y.shape)

y = to_categorical(
    y,
    num_classes=num_classes
)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

cnn = Sequential()

cnn.add(
    Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(128,128,3)
    )
)

cnn.add(
    MaxPooling2D((2,2))
)

cnn.add(
    Conv2D(
        64,
        (3,3),
        activation='relu'
    )
)

cnn.add(
    MaxPooling2D((2,2))
)

cnn.add(
    Conv2D(
        128,
        (3,3),
        activation='relu'
    )
)

cnn.add(
    MaxPooling2D((2,2))
)

cnn.add(Flatten())

cnn.add(
    Dense(
        128,
        activation='relu'
    )
)

cnn.add(
    Dropout(0.3)
)

cnn.add(
    Dense(
        num_classes,
        activation='softmax'
    )
)

cnn.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

cnn.summary()

history = cnn.fit(
    X_train,
    y_train,
    validation_data=(X_test,y_test),
    epochs=10,
    batch_size=32
)

loss, accuracy = cnn.evaluate(
    X_test,
    y_test
)

print("Accuracy:", accuracy)

pred = cnn.predict(X_test)

pred_classes = np.argmax(
    pred,
    axis=1
)

actual_classes = np.argmax(
    y_test,
    axis=1
)

print(
    classification_report(
        actual_classes,
        pred_classes,
        target_names=le.classes_
    )
)

cm = confusion_matrix(
    actual_classes,
    pred_classes
)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=False,
    cmap="Blues"
)

plt.title("Confusion Matrix")
plt.show()

plt.plot(
    history.history['accuracy']
)

plt.plot(
    history.history['val_accuracy']
)

plt.title("Model Accuracy")

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend([
    "Train",
    "Validation"
])

plt.show()
